spring:
  application:
    name: scw-ui

  redis:  #redis配置  
    host: 192.168.75.188
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis
    timeout:
      seconds: 1800
      
server:
  port: 10000

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true  # 支持注册中心使用ip-address[以后分布式发布时保证注册中心可以管理所有项目]
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
      